apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

patches:
  - patch: |
      - op: remove
        path: /spec/template/spec/nodeSelector
    target:
      kind: Job
      name: surg-rl-training
  - patch: |
      - op: remove
        path: /spec/template/spec/tolerations
    target:
      kind: Job
      name: surg-rl-training
  - patch: |
      - op: remove
        path: /spec/template/spec/containers/0/resources/requests/nvidia.com~1gpu
    target:
      kind: Job
      name: surg-rl-training
  - patch: |
      - op: remove
        path: /spec/template/spec/containers/0/resources/limits/nvidia.com~1gpu
    target:
      kind: Job
      name: surg-rl-training
  - patch: |
      - op: replace
        path: /spec/template/spec/containers/0/image
        value: ghcr.io/surg-rl/surg-rl:v0.3.0
    target:
      kind: Job
      name: surg-rl-training
