apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: surg-rl-checkpoints
  labels:
    app: surg-rl
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
  storageClassName: standard
